name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Deploy to gh-pages branch
        run: |
          git config --global user.email "zhubao315@users.noreply.github.com"
          git config --global user.name "zhubao315"
          git add -f dist/
          git commit -m "Deploy to GitHub Pages $(date)"
          git push -f origin HEAD:gh-pages